### PR TITLE
Move system to default profiles, and add light

### PR DESCRIPTION
**Pull request by iryanclarke**

### CODE REVIEW

**Comment by iryanclarke** [comment]
Not sure why this isn't building....

**Comment by CCAyl** [comment]
i'm guessing we will actually iron out our light profile values when anna gets back - is the plan to merge this just to have the typing done, and then we'll actual fill in the values after, and THEN update hw-admin?

**Comment by iryanclarke** [comment]
@CCAyl Ideally yeah, I think theres only `Button` and maybe one other that needs to make use of the `extended` colors. We could maybe even rename `light` to `inverse`???? Aka its light on dark, and dark on light

**Comment by CCAyl** [comment]
right yeah, since we have nothing settled for the light profile/extended colours, should we comment it out or remove the types until we actually have 'em? your call - approving!

**Review by CCAyl — APPROVED** [review]

**Comment by iryanclarke** [comment]
@CCAyl I'll leave in for now, just so that the `EXTENDED` types isn't the exact same, we can figure out exact naming and such later

**Pull request merged**
