### PR TITLE
Create light-ds3 tokens

### PR DESCRIPTION
**Pull request by bambie1**
Goal of this PR is to create a new `light.json` set of tokens for the DS4 updates. I've just duplicated the `light.json` tokens as `light-ds3.json`

### CODE REVIEW

**Review by alexandra-lim — APPROVED** [review]
Looking good! 😎

**Comment by iryanclarke** [comment]
This looks great!

**Review by iryanclarke — CHANGES_REQUESTED** [review]
Actually, could you export this new theme in the `themes.ts` file, and then copy the compiled result to `themes.js` and themes.d.ts` in the root?

**Review by iryanclarke — APPROVED** [review]
Noice!

**Pull request merged**
